descriptor-schema-version: "2.0"

info:
  name: CarControl
  description: "Control Cisco Car through Web interface"
  version: "1.0"
  author-link: "www.cisco.com"
  author-name: "Paul Beyleveld"

app:
  # Indicate app type (vm, paas, lxc etc.,)
  type: paas

  resources:
    profile: c1.small

    network:
      -
        interface-name: eth0
        ports:
            tcp: [8080]
    devices:
      -
        type: serial
        label: HOST_DEV1
        usage: Arduino Carcontrol Interface

  # Specify runtime and startup
  startup:
    runtime: python
    runtime-version: 2.7
    target: server.py
